---
title: "Ejemplo 1: Prediccion de Desempleo"
author: "Mateo Orozco Baldovino"
format: html
editor: visual
---

## Instalacion de librerias

La informacion de esto puede ser encontrada en el siguiente link

https://github.com/fersalme/series-tiempo-econometria/blob/main/01-modelo-STL1.R

```{r, eval=FALSE}
install.packages(c("tidyverse", "tsibble", "feasts", "fable"))
```

```{r}
library(tidyverse)
library(tsibble)
library(feasts)
library(fable)
```

# Importacion de la base de datos

```{r}
library(readr)
desempleo <- read_delim("data/Mercado laboral y población.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)
colnames(desempleo) <- c("periodo", "tasa_desempleo", "tasa_ocupacion")
head(desempleo)

```

```{r}
# temporalidad
desempleo <- desempleo |>
    mutate(periodo = yearmonth(periodo)) |>
    as_tsibble(index = periodo)
```

```{r}
# Numero de registros
cat("Numero de observaciones serie desempleo : ", nrow(desempleo))
cat("\nTemporalidad de la serie : ", range(year(desempleo$periodo)))
cat("\nTemporalidad fechas de la serie :", range(desempleo$periodo))
```
```{r}
# Ajustar la temporalidad de los datos
desempleo <- desempleo |>
  mutate(periodo = yearmonth(periodo)) |>
  as_tsibble(index = periodo) |>
  select(- tasa_ocupacion)

head(desempleo)
```
# Grafico
```{r}
# Grafico de la serie
# Tamaño de los graficos
options(repr.plot.width = 6, repr.plot.height = 4)
autoplot(desempleo)
```

```{r}
# Descomposicion STL de la serie

desempleo |>
  model(
    STL(tasa_desempleo ~ trend() + season(window ="periodic")) 
    )|>
  components()|>
    autoplot()
```

```{r}
# Ajustar el modelo usando TSLM (Time Series Linear Model - MCO para series de tiempo)
fit_mco <- desempleo |>
  model(
    mco_lineal = TSLM(tasa_desempleo ~ trend() + season())
  )

# Pronostico
pronostico <- forecast(fit_mco, h= 12) # 12 meses

pronostico |>
  autoplot(desempleo) +
  labs(title = "Pronóstico de Desempleo en Colombia (Modelo MCO)",
       subtitle = "Tendencia lineal + Estacionalidad fija",
       y = "Tasa de desempleo (%)") +
  theme_minimal()

```

```{r}
# 3. Reporte del modelo
report(fit_mco)
```
```{r}
# Modelo solo tendencia
fit_mco <- desempleo |>
  model(
    mco_stl = TSLM(tasa_desempleo ~ trend() + season()),
    mco_stl_covid = TSLM(tasa_desempleo ~ trend() + season() + I(periodo == yearmonth("2020-03-01"))),
    mco_trend = TSLM(tasa_desempleo ~ trend())
  )

# comparar modelos con criterios
glance(fit_mco) |>
  select(.model, adj_r_squared, AIC, BIC)
```

```{r}
# Medicion del redimiento del pronostico
accuracy(fit_mco) |>
  select(.model, MAE, RMSE, MAPE, MASE)
```




```{r}
# Validación train (80%) - test pronostico (20%)
index_cut <- floor(nrow(desempleo) * 0.8)
index_train <- seq(1, index_cut)
index_test <- seq(index_cut + 1, nrow(desempleo))

# set train
desempleo_train <- desempleo[index_train, ]
desempleo_test <- desempleo[index_test, ]

# Entrenar el modelo
fit_mco_train <- desempleo_train |>
  model(
    mco_stl = TSLM(tasa_desempleo ~ trend() + season()),
    mco_stl_covid = TSLM(tasa_desempleo ~ trend() + season() + I(periodo == yearmonth("2020-03-01"))),
    mco_trend = TSLM(tasa_desempleo ~ trend())
  )

# Prediccion de los modelos
h_pronostico <- length(index_test)
predict_mco_model <- forecast(fit_mco_train, h = h_pronostico)

# Comparar el rendimiento en el set test
accuracy(predict_mco_model, desempleo_test) |>
  select(.model, MAE, RMSE, MAPE, MASE)
```
```{r}
# Graficos pronostico train - test
predict_mco_model |>
  autoplot(desempleo_train, level = NULL) +
  labs(title = "Pronóstico de Desempleo en Colombia (Modelo MCO)",
       subtitle = "Comparación distintos modelos",
       y = "Tasa de desempleo (%)") +
  theme_minimal()
```




```{r}
# 4. Residuos del modelo MCO
fit_mco |> gg_tsresiduals()
```

